version:
  name: velociraptor
  version: 0.73.3
  build_time: "2024-12-03T08:03:35-05:00"
  compiler: go1.23.3
  system: linux
  architecture: amd64
Client:
  server_urls:
  - wss://192.168.149.205:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIRAMkwHHdvCu8coMlOXO39FEswDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MTIwMzEzMjQxNVoXDTM0
    MTIwMTEzMjQxNVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyA6iJmuZMGfXHwDJoO4N/8lXrP5AiFWH
    bLWhQaJzEZLbPzus+oQbb/ONcbOXYIG4AU8vu2AfnV9qeIexTUtVNLP2di9K9N5B
    hpRGYTZKhJK25mxVn6TSZPiClZcIecTMhZcSlIFl3SqB7/W+6l4MPSEHPthTB37I
    IUUMvVTo4lRMtx0jhJLdnEYRxb2LmncwsUKKgIu5dWGOcV9d5UqqdwG9YbxoGfRh
    MUEcSb5aWuTs/UJlBZF7VmO0XPIl6MnilZ1nZ8Sky0ughZ4xScznf8E28F85CVuW
    UAdAiOZpv7gtncRl/HoLK1fow+4sg9CoIbZRZAc12WZAdy1BUOYEQQIDAQABo4GM
    MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUk4AVERpmEkE6tKgQdGoFsNHr
    3IwwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
    KoZIhvcNAQELBQADggEBAH9jPyyQd8cAkwEClOYiPyGB5jQzcq+k8JSKaNoi/W9p
    SCBopechOo52ANgrfFI4Y69SFk6nGwlyRT99pvt2wENFKe1zztLv1htk4r9IpUsh
    FKjSkf5mo/VppYn5dSSu1/nSpVK7lPq/oKBwTcesQQKkg5LVt+SF7K94wuJh4xHH
    a/yVKSWsBWQQo/0ZgrSMAWxa0xz5i2bqdZmPEqOg3Q8j3H7M69FBoVphkIhZEVCT
    WgYRiVfrlkiJ5d6CKaxtnRkiimPD8HFaawstSPS16fgRTpnXi5nYMpaePYItVlfd
    rm5flpIQ4iYq59FJHN5BQVBZEXKZ+rV6eCtuuogfIjM=
    -----END CERTIFICATE-----
  nonce: Xsgzy+4VpXE=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: HKLM\SOFTWARE\Velocidex\Velociraptor
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  server_version:
    version: 0.73.3
    build_time: "2024-12-03T08:03:35-05:00"
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
